# Generated by Django 5.0.6 on 2025-10-25 11:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2025, 10, 25, 14, 43, 7, 160598), verbose_name='Опубликована'),
        ),
    ]
